[package]
name = "mini-interpreter"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = "1.0.63"
unicode-ident = "1.0"
itertools = { version = "0.13.0", optional = true }

[features]
default = []
bin = ["dep:itertools"]


[[bin]]
name = "lex"
required-features = ["bin"]
